[client]
toolbarMode = "minimal"

[server]
runOnSave = true
enableStaticServing = true

[ui]
hideTopBar = true

[theme]
base = "light"
primaryColor = "#ffc45c"
backgroundColor = "#f7f8fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#24313c"
